---
sudo: false
language: ruby
bundler_args: --without development system_tests
before_install: rm Gemfile.lock || true
rvm:
  - 2.4.1
script: bundle exec rake test
env:
  - PUPPET_GEM_VERSION="~> 5.3.2"
matrix:
  - rvm: 2.4.1
    env: PUPPET_GEM_VERSION="~> 5.3.2"
  - rvm: 2.4.2
    env: PUPPET_GEM_VERSION="~> 5.3.3"
